### ISSUE TITLE
Build error with the current Git 

### ISSUE THREAD

**Issue by xcom169** [csinkers/ualbion#25]
PS C:\Users\Chome\Downloads\My Games\ualbion-master> .\run.bat
C:\Users\Chome\Downloads\My Games\ualbion-master\build\UAlbion.Api\obj\Debug\netstandard2.0\.NETStandard,Version=v2.0.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [C:\Users\Chome\Downloads\My Games\ualbion-master\src\Api\UAlbion.Api.csproj]
C:\Users\Chome\Downloads\My Games\ualbion-master\build\UAlbion.Api\obj\Debug\netstandard2.0\UAlbion.Api.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [C:\Users\Chome\Downloads\My Games\ualbion-master\src\Api\UAlbion.Api.csproj]
C:\Users\Chome\Downloads\My Games\ualbion-master\build\UAlbion.Api\obj\Debug\netstandard2.0\UAlbion.Api.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [C:\Users\Chome\Downloads\My Games\ualbion-master\src\Api\UAlbion.Api.csproj]
C:\Users\Chome\Downloads\My Games\ualbion-master\build\UAlbion.Api\obj\Debug\netstandard2.0\UAlbion.Api.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [C:\Users\Chome\Downloads\My Games\ualbion-master\src\Api\UAlbion.Api.csproj]
C:\Users\Chome\Downloads\My Games\ualbion-master\build\UAlbion.Api\obj\Debug\netstandard2.0\UAlbion.Api.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute [C:\Users\Chome\Downloads\My Games\ualbion-master\src\Api\UAlbion.Api.csproj]
C:\Users\Chome\Downloads\My Games\ualbion-master\build\UAlbion.Api\obj\Debug\netstandard2.0\UAlbion.Api.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [C:\Users\Chome\Downloads\My Games\ualbion-master\src\Api\UAlbion.Api.csproj]
C:\Users\Chome\Downloads\My Games\ualbion-master\build\UAlbion.Api\obj\Debug\netstandard2.0\UAlbion.Api.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [C:\Users\Chome\Downloads\My Games\ualbion-master\src\Api\UAlbion.Api.csproj]
C:\Users\Chome\Downloads\My Games\ualbion-master\build\UAlbion.Api\obj\Debug\netstandard2.0\UAlbion.Api.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [C:\Users\Chome\Downloads\My Games\ualbion-master\src\Api\UAlbion.Api.csproj]

**Comment by csinkers** [comment]
What version of .NET are you using? i.e. what do you get if you enter `dotnet --version` at a command prompt?
I'm not seeing these errors after downloading a fresh zip of the repo, extracting and running run.bat

**Comment by xcom169** [comment]
I think I have multiple versions installed.
Maybe it's too fresh ?  v5.0.203

**Comment by csinkers** [comment]
It won't be that then, mine's working with v5.0.203
The file path of the first file is odd: netstandard2.0.NETStandard,Version=v2.0.AssemblyAttributes.cs
There should be a \ in there after "netstandard2.0" (build\UAlbion.Api\obj\Debug should only contain a netstandard2.0 directory, no files).

**Comment by xcom169** [comment]
PS C:\xx\Albion-master> dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

PS C:\Users\xxAlbion-master> dotnet --list-sdks
5.0.203 [C:\Program Files\dotnet\sdk]

**Comment by csinkers** [comment]
None of that looks like it should be causing a problem, if I download a fresh copy it works and github action builds are working on windows, linux and mac so it must be some weird environmental thing. Some things to try:
* cloning it with git rather than downloading the zip
* building with Visual Studio rather than run.bat / the dotnet cmdline utility (Community Edition or VS Code should both work) 
* if those don't work, try compiling using dotnet with full verbosity and I can take a look (upload the results to https://gist.github.com/ or something and link to it, it'll be too long for a comment). Running `dotnet run --project src\ualbion -v diag >build.log` should compile and write everything to "build.log".
